rbac:
  admin_roles:
    - all
  workflows:
    # Hello World Workflows
    - name: HelloWorld
      read_roles:
        - all
      execute_roles:
        - all
    - name: HelloWorldApproval
      read_roles:
        - all
      execute_roles:
        - all
    # NGC Workflows
    - name: BackupWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: DeployWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: TenantDeployWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: MultiDeployWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: BatchDeployWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: ReprovisionWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: DevicePasswordRotationWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: SiteCableValidationWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: DeviceCableValidationWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: VpcCreationWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: VpcDeletionWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: VpcAssignmentWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: VpcTenantChangeWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: PortLLDPInfoWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: InfinibandGetUnhealthyPortsWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: SwitchOSUpgradeWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: InfinibandCableValidationWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: InfinibandMlnxOSUpgradeWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: ConnectedHostMetadataWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: RedfishProvisioningWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: AIRCreateSimulationWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: AIRCreateBlueprintSimulationWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: AIRDeleteSimulationWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: AIRValidateSiteWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: ValidateHardwareWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: NVLinkSwitchFirmwareUpgradeWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: SitePasswordRotationWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: IBPKeyCreationWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: IBPKeyMemberAddWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: IBPKeyMemberUpdateWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: IBPKeyMemberDeleteWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: IBPortGuidDiscoveryWorkflow
      read_roles:
        - all
      execute_roles:
        - all
    - name: DiagnosticsWorkflow
      read_roles:
        - all
      execute_roles:
        - all

