# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Secret artifact generation.

Converts the user-defined network secrets in nv-config-manager-install.yaml into:
1. config-secrets.ini  -- site-scoped INI consumed by the render/temporal services
2. ESO vault paths     -- configSecrets entries for Helm values

Also provides a bootstrap scanner that reads the bundled
``config_contexts.yaml`` to discover which secret keys the ingest jobs
reference (e.g. ``root_password``, ``api_user_key``).
"""

from __future__ import annotations

import configparser
from pathlib import Path
from typing import Any

import yaml

from nv_config_manager_installer.schema import (
    NVConfigManagerInstallConfig,
    PasswordSource,
    SecretsMethod,
)


def _site_slug(name: str) -> str:
    return name.lower().replace(" ", "-")


# ---------------------------------------------------------------------------
# config-secrets.ini
# ---------------------------------------------------------------------------


def build_config_secrets_ini(
    config: NVConfigManagerInstallConfig,
    secrets_state: dict[str, str],
    existing_content: str | None = None,
) -> str:
    """Build the config-secrets.ini content.

    Format matches what src/nv_config_manager/temporal/common/secrets.py expects:
        [site.dc01]
        root_password_r1 = <value>
        api_user_key_r1 = <value>
        bgp_password_r1 = <value>
        ...
        hash_salt = <value>

    Args:
        config: The install config.
        secrets_state: Dict of secret key -> generated/manual value (only for
                       generate/manual sources; vault-sourced keys are omitted
                       because ESO provides them at runtime).
    """
    lines = [
        "# =================================================================",
        "# NVIDIA Config Manager Network Config Secrets",
        "# Auto-generated by nv-config-manager-installer",
        "# =================================================================",
        "",
    ]

    existing = _parse_existing_config_secrets(existing_content)

    for site in config.sites:
        slug = _site_slug(site.name)
        section = f"site.{slug}"
        lines.append(f"[{section}]")
        for entry in config.network_secrets:
            full_key = _entry_full_key(entry)
            if not full_key:
                continue
            value = _config_secret_value(existing, section, full_key, entry.source, secrets_state)
            if value:
                lines.append(f"{full_key} = {value}")
        hash_salt = _existing_value(existing, section, "hash_salt") or secrets_state.get(
            "hash_salt", ""
        )
        if hash_salt:
            lines.append(f"hash_salt = {hash_salt}")
        lines.append("")

    return "\n".join(lines)


def _entry_full_key(entry: Any) -> str:
    """Return the config-secrets.ini field for a network secret entry."""
    if not entry.secret_key:
        return ""
    if not entry.rotation:
        return entry.secret_key
    return f"{entry.secret_key}_{entry.rotation}"


def _parse_existing_config_secrets(existing_content: str | None) -> configparser.ConfigParser:
    """Parse existing config-secrets.ini content, if present."""
    parser = configparser.ConfigParser(interpolation=None)
    if not existing_content:
        return parser
    try:
        parser.read_string(existing_content)
    except configparser.Error:
        return configparser.ConfigParser(interpolation=None)
    return parser


def _existing_value(
    existing: configparser.ConfigParser,
    section: str,
    key: str,
) -> str:
    if existing.has_option(section, key):
        return existing.get(section, key)
    return ""


def _config_secret_value(
    existing: configparser.ConfigParser,
    section: str,
    full_key: str,
    source: PasswordSource,
    secrets_state: dict[str, str],
) -> str:
    if source != PasswordSource.MANUAL:
        existing_value = _existing_value(existing, section, full_key)
        if existing_value:
            return existing_value
    return secrets_state.get(full_key, "")


# ---------------------------------------------------------------------------
# ESO vault paths (for Helm values configSecrets section)
# ---------------------------------------------------------------------------


def build_eso_config_secrets(config: NVConfigManagerInstallConfig) -> dict[str, Any]:
    """Build the ``configSecrets`` section for Helm values.

    The chart reads ``secrets.vault.configSecrets`` so the caller must place
    the returned dict at that path.  Returns a flat dict:

        {"enabled": True, "sites": [{"name": "dc01", "path": "..."}]}
    """
    if config.secrets.method != SecretsMethod.ESO or not config.sites:
        return {"enabled": False}

    sites = []
    for site in config.sites:
        vault_path = site.vault_path
        if not vault_path:
            env = config.cluster.environment
            vault_path = f"{env}/site/{_site_slug(site.name)}/config_secrets"
        sites.append({"name": site.name, "path": vault_path})

    return {"enabled": True, "sites": sites}


def get_vault_sourced_keys(config: NVConfigManagerInstallConfig) -> list[tuple[str, str]]:
    """Return (secret_key, rotation) pairs that come from Vault (not generated)."""
    keys: list[tuple[str, str]] = []
    for entry in config.network_secrets:
        if entry.source == PasswordSource.VAULT and entry.secret_key:
            keys.append((entry.secret_key, entry.rotation))
    return keys


# ---------------------------------------------------------------------------
# Bootstrap config context scanner
# ---------------------------------------------------------------------------

_CONFIG_CONTEXTS_REL = Path("components/nautobot/nv_config_manager_jobs/data/config_contexts.yaml")


def _humanize_key(secret_key: str) -> str:
    """Turn an underscore-separated key into a human-readable label."""
    return secret_key.replace("_", " ").title()


def _extract_password_keys(
    data: list[dict],
) -> list[tuple[str, str, str]]:
    """Extract unique (display_name, secret_key, rotation) from config context entries."""
    seen: set[str] = set()
    results: list[tuple[str, str, str]] = []
    for entry in data:
        mappings = (entry.get("data") or {}).get("password_mappings")
        if not isinstance(mappings, dict):
            continue
        for user_cfg in mappings.values():
            if not isinstance(user_cfg, dict):
                continue
            key = user_cfg.get("password", "")
            rotation = user_cfg.get("rotation", "r1")
            if key and key not in seen:
                seen.add(key)
                results.append((_humanize_key(key), key, rotation))
    return results


def scan_bootstrap_secrets(
    project_root: Path | None = None,
) -> list[tuple[str, str, str]]:
    """Scan bundled ``config_contexts.yaml`` for password keys.

    Returns a list of ``(display_name, secret_key, rotation)`` tuples
    discovered from ``password_mappings`` entries in config contexts.
    Duplicates (by secret_key) are removed.
    """
    cc_file = _find_config_contexts(project_root)
    if cc_file is None:
        return []

    try:
        with open(cc_file) as f:
            data = yaml.safe_load(f)
    except Exception:
        return []

    if not isinstance(data, list):
        return []

    return _extract_password_keys(data)


def _find_config_contexts(project_root: Path | None) -> Path | None:
    """Locate the bundled ``config_contexts.yaml``.

    When *project_root* is given explicitly, only that directory is checked.
    Otherwise the function walks upward from CWD.
    """
    if project_root:
        candidate = project_root / _CONFIG_CONTEXTS_REL
        return candidate if candidate.is_file() else None

    cur = Path.cwd().resolve()
    for _ in range(20):
        candidate = cur / _CONFIG_CONTEXTS_REL
        if candidate.is_file():
            return candidate
        parent = cur.parent
        if parent == cur:
            break
        cur = parent
    return None
