"use client";

import { useQuery } from "@tanstack/react-query";
import {
  Activity,
  AlertTriangle,
  Bot,
  FileText,
  Workflow,
} from "lucide-react";
import { GreetingHero } from "@/components/greeting-hero";
import { HeroBriefing } from "@/components/hero-briefing";
import { SummaryTile } from "@/components/cards/summary-tile";
import { api } from "@/lib/api";

/**
 * Home dashboard.
 *
 * Composition:
 *   1. Cinematic hero with the AI core PNG occupying the right edge.
 *   2. The current daily briefing, in full. The operator should not have
 *      to click through to read it — it's the headline of the page.
 *   3. A grid of summary tiles — one bite-sized signal per tile,
 *      each linking through to its detail page. Notifications + the
 *      AI assistant live in the right rail, not here.
 */
export default function HomePage() {
  const { data: alerts } = useQuery({
    queryKey: ["alerts", "all"],
    queryFn: () => api.alerts.list(),
    refetchInterval: 20_000,
  });
  const { data: incidents } = useQuery({
    queryKey: ["incidents", "open"],
    queryFn: () => api.infra.incidents({ status: "open" }),
    refetchInterval: 30_000,
  });
  const { data: agents } = useQuery({
    queryKey: ["agents", "all"],
    queryFn: () => api.agents.list(),
    refetchInterval: 60_000,
  });
  const { data: runs } = useQuery({
    queryKey: ["workflow-runs", "home"],
    queryFn: () => api.workflows.runs(),
    refetchInterval: 15_000,
  });
  const { data: events } = useQuery({
    queryKey: ["events", "24h"],
    queryFn: () => api.events.list({ since_hours: 24, limit: 200 }),
    refetchInterval: 30_000,
  });
  const { data: briefings } = useQuery({
    queryKey: ["briefings", "infra"],
    queryFn: () => api.briefings.list("infra"),
    refetchInterval: 5 * 60_000,
  });

  const openAlerts = (alerts ?? []).filter((a) => a.status === "open");
  const critical = openAlerts.filter((a) => a.severity === "critical").length;
  const running = (runs ?? []).filter(
    (r) => r.status === "running" || r.status === "waiting_for_approval"
  ).length;
  const succeeded = (runs ?? []).filter((r) => r.status === "succeeded").length;
  const eventsTotal = events?.length ?? 0;

  // 24h event histogram for the activity sparkline
  const buckets = bucketize(events ?? []);

  return (
    <div className="space-y-6 max-w-[1400px]">
      <GreetingHero alertCount={critical} />

      {/* The daily briefing, rendered in full. This is the headline of
       *  the home page — what changed since you last looked, in plain
       *  English, generated by an agent. */}
      <HeroBriefing channel="infra" />

      <div className="grid grid-cols-2 lg:grid-cols-3 gap-4">
        <SummaryTile
          href="/agents"
          icon={Bot}
          label="Active agents"
          value={agents?.length ?? 0}
          hint="Workforce online"
        />
        <SummaryTile
          href="/operations"
          icon={AlertTriangle}
          label="Open incidents"
          value={incidents?.length ?? 0}
          hint={critical > 0 ? `${critical} critical` : "All clear"}
          intent={critical > 0 ? "negative" : "positive"}
        />
        <SummaryTile
          href="/alerts"
          icon={Activity}
          label="Operational activity (24h)"
          value={eventsTotal}
          hint="events ingested"
          spark={buckets}
        />
        <SummaryTile
          href="/automations"
          icon={Workflow}
          label="Workflows running"
          value={running}
          hint={`${succeeded} completed today`}
        />
        <SummaryTile
          href="/reports"
          icon={FileText}
          label="Briefings on file"
          value={briefings?.length ?? 0}
          hint="all archived runs"
        />
      </div>
    </div>
  );
}

/**
 * Coarse 6-bucket histogram of event counts over the last 24h. Used as
 * the sparkline data on the Operational activity tile.
 */
function bucketize(events: { occurred_at: string }[]): number[] {
  const N = 6;
  const buckets = Array(N).fill(0);
  const cutoff = Date.now() - 24 * 60 * 60 * 1000;
  for (const e of events) {
    const t = new Date(e.occurred_at).getTime();
    if (t < cutoff) continue;
    const idx = Math.min(N - 1, Math.floor(((t - cutoff) / (24 * 60 * 60 * 1000)) * N));
    buckets[idx] += 1;
  }
  return buckets;
}
