"""Per-tenant Nautobot K8s manifests.

Pure functions: take a ``TenantParams`` dataclass + the bootstrap
credentials, return manifest dicts. No K8s API calls, no I/O — that
lives in :mod:`nautobot_controller.k8s`. Splitting them keeps the
manifest shapes easy to unit-test (the existing test pattern just
asserts on the returned dict, no httpx/kubernetes-asyncio mocking).

The manifest set mirrors the existing shared-Nautobot stack at
``deploy/k8s/nautobot/`` — same images, same env vars, same probe
shapes. The differences are all parameterisations:

* The ``namespace`` becomes ``nautobot-<slug>`` instead of
  ``nautobot``.
* The hostname in ``NAUTOBOT_ALLOWED_HOSTS`` /
  ``NAUTOBOT_CSRF_TRUSTED_ORIGINS`` becomes the per-tenant
  subdomain.
* All credentials (POSTGRES_PASSWORD, NAUTOBOT_SECRET_KEY,
  NAUTOBOT_SUPERUSER_PASSWORD, NAUTOBOT_SUPERUSER_API_TOKEN) are
  generated by the controller at provision time, stored encrypted
  in the ``nautobot_tenants`` row, and stamped into a per-namespace
  Secret. The Nautobot entrypoint's ``CREATE_SUPERUSER=true`` path
  then bootstraps the admin user with the *exact* API token we
  passed — no separate "mint a token" step.

In customer-cluster mode (Phase 2) we still generate all manifests
but skip the public Ingress (set ``include_ingress=False`` on
:func:`build_all`) — daalu-api reaches the workspace through the wg
tunnel + in-cluster Service DNS.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class TenantParams:
    """Inputs to the manifest builders.

    Carried separately from :class:`NautobotTenant` so the manifest
    code is pure and trivially testable; the controller's reconcile
    loop builds this dataclass from the DB row.
    """

    # Daalu tenant slug — used to derive the namespace, hostname,
    # and labels. Must already be DNS-1123 compliant (the daalu
    # tenant validation enforces that).
    slug: str
    # Daalu tenant display name — surfaced in Nautobot's
    # ``description`` field on the (single) Nautobot Tenant row that
    # the bootstrap Job creates.
    name: str
    # Where the stack lives. None → operator cluster (public
    # ingress + cert-manager). Anything else (the cluster tunnel
    # id) → customer cluster (no ingress).
    target_cluster_tunnel_id: str | None = None
    # ``<slug>.sot.example.com`` for operator-cluster; None for
    # customer-cluster (daalu reaches via Service DNS + wg).
    hostname: str | None = None

    # Bootstrap credentials — generated by the controller at
    # provision time, then reused on every reconcile so the
    # Postgres/Nautobot pair don't lose their auth when manifests
    # are re-applied.
    postgres_password: str = ""
    nautobot_secret_key: str = ""
    admin_password: str = ""
    admin_token: str = ""

    # Image pin. The shared-Nautobot deploy lives at
    # ``networktocode/nautobot:2.2-py3.11``; per-tenant follows the
    # same default so a single CVE bump rolls every tenant.
    nautobot_image: str = "networktocode/nautobot:2.2-py3.11"
    postgres_image: str = "postgres:16-alpine"
    redis_image: str = "redis:7-alpine"

    # Storage for the per-tenant Postgres PVC. Small default;
    # the wizard can offer larger tiers later.
    postgres_storage: str = "20Gi"
    # Storage for the Nautobot media volume (uploads, custom
    # field attachments). Small — most tenants never hit a GB.
    nautobot_storage: str = "5Gi"

    # Operator-side resource caps. Conservative; the
    # single-node box can hold ~30 of these.
    nautobot_cpu_request: str = "100m"
    nautobot_cpu_limit: str = "1"
    nautobot_mem_request: str = "256Mi"
    nautobot_mem_limit: str = "1Gi"

    # Optional extra labels — every manifest gets these so a
    # ``kubectl get all -l daalu.io/nautobot-tenant=<slug>`` works.
    extra_labels: dict[str, str] = field(default_factory=dict)


# ── Namespace + Secret ─────────────────────────────────────────────────


def namespace_for_slug(slug: str) -> str:
    """The deterministic namespace name for a tenant.

    Kept as a free function so callers (controller reconcile loop,
    teardown helpers, the engineer doc's verification commands) all
    derive the same name from one place.
    """
    return f"nautobot-{slug}"


def build_namespace(p: TenantParams) -> dict[str, Any]:
    return {
        "apiVersion": "v1",
        "kind": "Namespace",
        "metadata": {
            "name": namespace_for_slug(p.slug),
            "labels": _labels(p, role="namespace"),
        },
    }


def build_secret(p: TenantParams) -> dict[str, Any]:
    """The per-namespace credentials Secret.

    Holds every value the per-tenant Nautobot pod + Postgres need.
    The controller writes this once at provision time and re-asserts
    it on every reconcile — rewriting with identical values is a
    no-op against the K8s control plane.

    NB: ``stringData`` (not ``data``) so we don't have to base64 the
    values ourselves; K8s does it. SOPS / encryption-at-rest live at
    the daalu DB layer (the ciphertext columns on nautobot_tenants),
    not on the K8s Secret itself.
    """
    return {
        "apiVersion": "v1",
        "kind": "Secret",
        "type": "Opaque",
        "metadata": {
            "name": "nautobot-secrets",
            "namespace": namespace_for_slug(p.slug),
            "labels": _labels(p, role="secret"),
        },
        "stringData": {
            "POSTGRES_PASSWORD": p.postgres_password,
            "NAUTOBOT_DB_PASSWORD": p.postgres_password,
            "NAUTOBOT_SECRET_KEY": p.nautobot_secret_key,
            "NAUTOBOT_SUPERUSER_PASSWORD": p.admin_password,
            # The Nautobot entrypoint accepts an explicit API token to
            # use for the bootstrapped superuser. We pass our
            # pre-generated value so the controller knows exactly
            # which token to hand back to daalu-api on completion —
            # no second round-trip to mint one.
            "NAUTOBOT_SUPERUSER_API_TOKEN": p.admin_token,
            # Email is required by the bootstrap but never used.
            "NAUTOBOT_SUPERUSER_EMAIL": "admin@daalu.io",
        },
    }


# ── ConfigMap (env) ────────────────────────────────────────────────────


def build_configmap(p: TenantParams) -> dict[str, Any]:
    """Non-secret env. Mirrors deploy/k8s/nautobot/configmap.yaml.

    The hostname-derived fields change per tenant; everything else
    is constant. ALLOWED_HOSTS uses *space* separation (not comma) —
    Nautobot's settings parser splits on whitespace.
    """
    ns = namespace_for_slug(p.slug)
    public_host = p.hostname or ""
    allowed = ["nautobot", f"nautobot.{ns}.svc.cluster.local", "localhost", "127.0.0.1"]
    csrf: list[str] = []
    if public_host:
        allowed.insert(0, public_host)
        csrf.append(f"https://{public_host}")
    return {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {
            "name": "nautobot-env",
            "namespace": ns,
            "labels": _labels(p, role="configmap"),
        },
        "data": {
            "NAUTOBOT_DB_HOST": f"nautobot-postgres.{ns}.svc.cluster.local",
            "NAUTOBOT_DB_PORT": "5432",
            "NAUTOBOT_DB_NAME": "nautobot",
            "NAUTOBOT_DB_USER": "nautobot",
            "NAUTOBOT_REDIS_HOST": f"nautobot-redis.{ns}.svc.cluster.local",
            "NAUTOBOT_REDIS_PORT": "6379",
            "NAUTOBOT_ALLOWED_HOSTS": " ".join(allowed),
            "NAUTOBOT_CSRF_TRUSTED_ORIGINS": " ".join(csrf),
            "NAUTOBOT_CREATE_SUPERUSER": "true",
            "NAUTOBOT_SUPERUSER_NAME": "admin",
        },
    }


# ── Postgres ────────────────────────────────────────────────────────────


def build_postgres(p: TenantParams) -> list[dict[str, Any]]:
    """Postgres PVC + StatefulSet + headless Service.

    One Postgres per tenant — operationally heavier than a shared
    cluster with per-tenant databases, but it preserves the strongest
    isolation guarantee (a bad Postgres role-grant can't cross
    tenants). If the per-tenant pod count starts to bite, swap in
    CloudNativePG without changing the rest of this module — the
    Service name (``nautobot-postgres``) is what Nautobot reads.
    """
    ns = namespace_for_slug(p.slug)
    pvc = {
        "apiVersion": "v1",
        "kind": "PersistentVolumeClaim",
        "metadata": {
            "name": "nautobot-postgres-data",
            "namespace": ns,
            "labels": _labels(p, role="postgres"),
        },
        "spec": {
            "accessModes": ["ReadWriteOnce"],
            "resources": {"requests": {"storage": p.postgres_storage}},
        },
    }
    sts = {
        "apiVersion": "apps/v1",
        "kind": "StatefulSet",
        "metadata": {
            "name": "nautobot-postgres",
            "namespace": ns,
            "labels": _labels(p, role="postgres"),
        },
        "spec": {
            "serviceName": "nautobot-postgres",
            "replicas": 1,
            "selector": {"matchLabels": {"app": "nautobot-postgres"}},
            "template": {
                "metadata": {
                    "labels": {
                        "app": "nautobot-postgres",
                        **_labels(p, role="postgres"),
                    }
                },
                "spec": {
                    "automountServiceAccountToken": False,
                    "securityContext": {
                        "runAsNonRoot": True,
                        "runAsUser": 999,
                        "runAsGroup": 999,
                        "fsGroup": 999,
                    },
                    "containers": [
                        {
                            "name": "postgres",
                            "image": p.postgres_image,
                            "env": [
                                {"name": "POSTGRES_DB", "value": "nautobot"},
                                {"name": "POSTGRES_USER", "value": "nautobot"},
                                {
                                    "name": "POSTGRES_PASSWORD",
                                    "valueFrom": {
                                        "secretKeyRef": {
                                            "name": "nautobot-secrets",
                                            "key": "POSTGRES_PASSWORD",
                                        }
                                    },
                                },
                                {
                                    "name": "PGDATA",
                                    "value": "/var/lib/postgresql/data/pgdata",
                                },
                            ],
                            "ports": [{"containerPort": 5432}],
                            "readinessProbe": {
                                "exec": {
                                    "command": ["pg_isready", "-U", "nautobot"],
                                },
                                "initialDelaySeconds": 10,
                                "periodSeconds": 5,
                            },
                            "volumeMounts": [
                                {
                                    "name": "data",
                                    "mountPath": "/var/lib/postgresql/data",
                                }
                            ],
                            "resources": {
                                "requests": {"cpu": "50m", "memory": "256Mi"},
                                "limits": {"cpu": "1", "memory": "1Gi"},
                            },
                        }
                    ],
                    "volumes": [
                        {
                            "name": "data",
                            "persistentVolumeClaim": {
                                "claimName": "nautobot-postgres-data"
                            },
                        }
                    ],
                },
            },
        },
    }
    svc = {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {
            "name": "nautobot-postgres",
            "namespace": ns,
            "labels": _labels(p, role="postgres"),
        },
        "spec": {
            "selector": {"app": "nautobot-postgres"},
            "ports": [{"port": 5432, "targetPort": 5432}],
            # Headless so the StatefulSet pod gets a stable DNS name
            # (nautobot-postgres-0.nautobot-postgres). Nautobot only
            # uses the Service DNS, but a future read-replica setup
            # would want pod-level addressing.
            "clusterIP": "None",
        },
    }
    return [pvc, sts, svc]


# ── Redis ───────────────────────────────────────────────────────────────


def build_redis(p: TenantParams) -> list[dict[str, Any]]:
    ns = namespace_for_slug(p.slug)
    dep = {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {
            "name": "nautobot-redis",
            "namespace": ns,
            "labels": _labels(p, role="redis"),
        },
        "spec": {
            "replicas": 1,
            "selector": {"matchLabels": {"app": "nautobot-redis"}},
            "template": {
                "metadata": {
                    "labels": {
                        "app": "nautobot-redis",
                        **_labels(p, role="redis"),
                    }
                },
                "spec": {
                    "automountServiceAccountToken": False,
                    "containers": [
                        {
                            "name": "redis",
                            "image": p.redis_image,
                            "ports": [{"containerPort": 6379}],
                            "resources": {
                                "requests": {"cpu": "20m", "memory": "64Mi"},
                                "limits": {"cpu": "200m", "memory": "256Mi"},
                            },
                        }
                    ],
                },
            },
        },
    }
    svc = {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {
            "name": "nautobot-redis",
            "namespace": ns,
            "labels": _labels(p, role="redis"),
        },
        "spec": {
            "selector": {"app": "nautobot-redis"},
            "ports": [{"port": 6379, "targetPort": 6379}],
        },
    }
    return [dep, svc]


# ── Nautobot web / worker / scheduler ──────────────────────────────────


def _nautobot_envfrom() -> list[dict[str, Any]]:
    return [
        {"configMapRef": {"name": "nautobot-env"}},
        {"secretRef": {"name": "nautobot-secrets"}},
    ]


def _nautobot_pod_security() -> dict[str, Any]:
    # Mirrors deploy/k8s/nautobot/web/deployment.yaml — the upstream
    # image runs as uid/gid 999.
    return {
        "runAsNonRoot": True,
        "runAsUser": 999,
        "runAsGroup": 999,
        "fsGroup": 999,
    }


def build_nautobot_web(p: TenantParams) -> list[dict[str, Any]]:
    ns = namespace_for_slug(p.slug)
    host = p.hostname or f"nautobot.{ns}.svc.cluster.local"
    probe = {
        "httpGet": {
            "path": "/health/",
            "port": 8080,
            "httpHeaders": [{"name": "Host", "value": host}],
        },
        "initialDelaySeconds": 30,
        "periodSeconds": 10,
        "timeoutSeconds": 5,
    }
    dep = {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {
            "name": "nautobot",
            "namespace": ns,
            "labels": _labels(p, role="nautobot-web"),
        },
        "spec": {
            "replicas": 1,
            "selector": {"matchLabels": {"app": "nautobot"}},
            "template": {
                "metadata": {
                    "labels": {"app": "nautobot", **_labels(p, role="nautobot-web")}
                },
                "spec": {
                    "automountServiceAccountToken": False,
                    "securityContext": _nautobot_pod_security(),
                    "initContainers": [
                        {
                            "name": "migrate",
                            "image": p.nautobot_image,
                            "command": ["nautobot-server", "migrate"],
                            "envFrom": _nautobot_envfrom(),
                            "resources": {
                                "requests": {"cpu": "100m", "memory": "256Mi"},
                                "limits": {"cpu": "1", "memory": "1Gi"},
                            },
                        }
                    ],
                    "containers": [
                        {
                            "name": "nautobot",
                            "image": p.nautobot_image,
                            "ports": [{"containerPort": 8080}],
                            "envFrom": _nautobot_envfrom(),
                            "readinessProbe": probe,
                            "livenessProbe": {
                                **probe,
                                "initialDelaySeconds": 90,
                                "periodSeconds": 30,
                                "timeoutSeconds": 10,
                            },
                            "resources": {
                                "requests": {
                                    "cpu": p.nautobot_cpu_request,
                                    "memory": p.nautobot_mem_request,
                                },
                                "limits": {
                                    "cpu": p.nautobot_cpu_limit,
                                    "memory": p.nautobot_mem_limit,
                                },
                            },
                        }
                    ],
                },
            },
        },
    }
    svc = {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {
            "name": "nautobot",
            "namespace": ns,
            "labels": _labels(p, role="nautobot-web"),
        },
        "spec": {
            "selector": {"app": "nautobot"},
            "ports": [{"port": 80, "targetPort": 8080}],
        },
    }
    return [dep, svc]


def build_nautobot_worker(p: TenantParams) -> dict[str, Any]:
    ns = namespace_for_slug(p.slug)
    return {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {
            "name": "nautobot-worker",
            "namespace": ns,
            "labels": _labels(p, role="nautobot-worker"),
        },
        "spec": {
            "replicas": 1,
            "selector": {"matchLabels": {"app": "nautobot-worker"}},
            "template": {
                "metadata": {
                    "labels": {
                        "app": "nautobot-worker",
                        **_labels(p, role="nautobot-worker"),
                    }
                },
                "spec": {
                    "automountServiceAccountToken": False,
                    "securityContext": _nautobot_pod_security(),
                    "containers": [
                        {
                            "name": "worker",
                            "image": p.nautobot_image,
                            "command": ["nautobot-server", "celery", "worker"],
                            "envFrom": _nautobot_envfrom(),
                            "resources": {
                                "requests": {"cpu": "50m", "memory": "256Mi"},
                                "limits": {"cpu": "500m", "memory": "1Gi"},
                            },
                        }
                    ],
                },
            },
        },
    }


def build_nautobot_scheduler(p: TenantParams) -> dict[str, Any]:
    ns = namespace_for_slug(p.slug)
    return {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {
            "name": "nautobot-scheduler",
            "namespace": ns,
            "labels": _labels(p, role="nautobot-scheduler"),
        },
        "spec": {
            "replicas": 1,
            "selector": {"matchLabels": {"app": "nautobot-scheduler"}},
            "template": {
                "metadata": {
                    "labels": {
                        "app": "nautobot-scheduler",
                        **_labels(p, role="nautobot-scheduler"),
                    }
                },
                "spec": {
                    "automountServiceAccountToken": False,
                    "securityContext": _nautobot_pod_security(),
                    "containers": [
                        {
                            "name": "scheduler",
                            "image": p.nautobot_image,
                            "command": ["nautobot-server", "celery", "beat"],
                            "envFrom": _nautobot_envfrom(),
                            "resources": {
                                "requests": {"cpu": "20m", "memory": "128Mi"},
                                "limits": {"cpu": "200m", "memory": "512Mi"},
                            },
                        }
                    ],
                },
            },
        },
    }


# ── Ingress (operator-cluster only) ────────────────────────────────────


def build_ingress(p: TenantParams) -> dict[str, Any]:
    """Public traefik Ingress + cert-manager HTTP-01 TLS.

    Only used in operator-cluster mode. Customer-cluster mode skips
    this entirely — daalu-api reaches the pod via the wg tunnel and
    in-cluster Service DNS, no public hostname required.
    """
    if not p.hostname:
        raise ValueError("build_ingress requires hostname (operator-cluster mode)")
    ns = namespace_for_slug(p.slug)
    return {
        "apiVersion": "networking.k8s.io/v1",
        "kind": "Ingress",
        "metadata": {
            "name": "nautobot",
            "namespace": ns,
            "labels": _labels(p, role="ingress"),
            "annotations": {
                "cert-manager.io/cluster-issuer": "letsencrypt-prod",
            },
        },
        "spec": {
            "ingressClassName": "traefik",
            "tls": [
                {
                    "hosts": [p.hostname],
                    "secretName": f"{p.slug}-sot-daalu-io-tls",
                }
            ],
            "rules": [
                {
                    "host": p.hostname,
                    "http": {
                        "paths": [
                            {
                                "path": "/",
                                "pathType": "Prefix",
                                "backend": {
                                    "service": {
                                        "name": "nautobot",
                                        "port": {"number": 80},
                                    }
                                },
                            }
                        ]
                    },
                }
            ],
        },
    }


# ── NetworkPolicy ──────────────────────────────────────────────────────


def build_networkpolicy(p: TenantParams) -> list[dict[str, Any]]:
    """Default-deny posture + the narrow allows we actually need.

    Postgres/Redis are intra-namespace (the Nautobot pods are the only
    callers); web pod takes ingress from traefik (operator-cluster) or
    daalu-api over the wg tunnel (customer-cluster — the policy allows
    the relevant CIDR via the kube-system DNS allowlist below).
    """
    ns = namespace_for_slug(p.slug)
    out: list[dict[str, Any]] = [
        {
            "apiVersion": "networking.k8s.io/v1",
            "kind": "NetworkPolicy",
            "metadata": {"name": "default-deny", "namespace": ns},
            "spec": {"podSelector": {}, "policyTypes": ["Ingress", "Egress"]},
        },
        # Intra-namespace pod-to-pod (web → postgres, web → redis,
        # worker → postgres, worker → redis).
        {
            "apiVersion": "networking.k8s.io/v1",
            "kind": "NetworkPolicy",
            "metadata": {"name": "allow-intra-ns", "namespace": ns},
            "spec": {
                "podSelector": {},
                "policyTypes": ["Ingress", "Egress"],
                "ingress": [{"from": [{"podSelector": {}}]}],
                "egress": [{"to": [{"podSelector": {}}]}],
            },
        },
        # DNS + general HTTPS egress so Nautobot can fetch updates,
        # contact a Git source for Apps, etc.
        {
            "apiVersion": "networking.k8s.io/v1",
            "kind": "NetworkPolicy",
            "metadata": {"name": "allow-egress-dns-https", "namespace": ns},
            "spec": {
                "podSelector": {"matchLabels": {"app": "nautobot"}},
                "policyTypes": ["Egress"],
                "egress": [
                    {
                        "to": [
                            {
                                "namespaceSelector": {
                                    "matchLabels": {
                                        "kubernetes.io/metadata.name": "kube-system"
                                    }
                                }
                            }
                        ],
                        "ports": [
                            {"protocol": "UDP", "port": 53},
                            {"protocol": "TCP", "port": 53},
                        ],
                    },
                    {
                        "to": [{"ipBlock": {"cidr": "0.0.0.0/0"}}],
                        "ports": [{"protocol": "TCP", "port": 443}],
                    },
                ],
            },
        },
    ]
    if p.hostname:
        out.append(
            {
                "apiVersion": "networking.k8s.io/v1",
                "kind": "NetworkPolicy",
                "metadata": {"name": "allow-traefik-to-web", "namespace": ns},
                "spec": {
                    "podSelector": {"matchLabels": {"app": "nautobot"}},
                    "policyTypes": ["Ingress"],
                    "ingress": [
                        {
                            "from": [
                                {
                                    "namespaceSelector": {
                                        "matchLabels": {
                                            "kubernetes.io/metadata.name": "kube-system"
                                        }
                                    }
                                }
                            ],
                            "ports": [{"protocol": "TCP", "port": 8080}],
                        }
                    ],
                },
            }
        )
    else:
        # Customer-cluster mode: daalu-api reaches the web pod through
        # the wg tunnel. The exact source is the wireguard interface
        # address on the customer cluster; lock to a broad allow on
        # port 8080 and rely on the tunnel for the perimeter.
        out.append(
            {
                "apiVersion": "networking.k8s.io/v1",
                "kind": "NetworkPolicy",
                "metadata": {"name": "allow-cluster-to-web", "namespace": ns},
                "spec": {
                    "podSelector": {"matchLabels": {"app": "nautobot"}},
                    "policyTypes": ["Ingress"],
                    "ingress": [
                        {
                            "from": [{"ipBlock": {"cidr": "0.0.0.0/0"}}],
                            "ports": [{"protocol": "TCP", "port": 8080}],
                        }
                    ],
                },
            }
        )
    return out


# ── Bundle helper ──────────────────────────────────────────────────────


def build_all(
    p: TenantParams, *, include_ingress: bool | None = None
) -> list[dict[str, Any]]:
    """Return the full stack of manifests in apply order.

    Order matters when applying for the first time: namespace →
    Secret/ConfigMap → Postgres/Redis (Nautobot's initContainer
    waits on Postgres readiness) → Nautobot pods → Ingress.
    Re-applies in any order are safe because each manifest is named
    independently and server-side apply tolerates re-asserts.

    ``include_ingress`` defaults to True when ``p.hostname`` is set
    (operator-cluster mode) and False otherwise.
    """
    if include_ingress is None:
        include_ingress = bool(p.hostname)
    out: list[dict[str, Any]] = [
        build_namespace(p),
        build_secret(p),
        build_configmap(p),
        *build_postgres(p),
        *build_redis(p),
        *build_nautobot_web(p),
        build_nautobot_worker(p),
        build_nautobot_scheduler(p),
        *build_networkpolicy(p),
    ]
    if include_ingress:
        out.append(build_ingress(p))
    return out


# ── helpers ────────────────────────────────────────────────────────────


def _labels(p: TenantParams, *, role: str) -> dict[str, str]:
    base = {
        "daalu.io/nautobot-tenant": p.slug,
        "daalu.io/role": role,
        "app.kubernetes.io/part-of": "daalu-nautobot",
    }
    base.update(p.extra_labels)
    return base
